language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
script:
  - mkdir ~/.aws
  - cp test/data/credentials ~/.aws/
  - python -m pytest